### ISSUE TITLE
Notification from User Applications not working after fully discharge.  

### ISSUE THREAD

**Issue by boierito** [c22dev/Geranium#10]
Hi dev,

I know that the title could be weird but I didnt change anything from my device. My conclusion is that the cleaner removes something that made me this. I used 1.0 and this happens after use this Tool. My daemon list is empty. 

I dont have any screenshot or something else. 

My device is iPhone X, 15.7.1. 

Any discord that where can we talk this? My username is boierito

**Comment by c22dev** [comment]
This is a known issue on iOS 15 specifically. 
If your daemon list is empty, you could try to hit the reset button in the manager (top-left icon)
The issue you described with the cleaner should be fixed in next release (1.1.1) but in the meantime you can try using latest bootstrap's commit's ipa then press fix app notification in it's settings.

When you cleaned using Geranium, did you cleaned app leftover caches ? 

My username is `c22dev` on discord but we can totally try to fix this here.

**Comment by boierito** [comment]
When i clean, I pressed all the checks so that could be a problem. I am not interested on the semi-jailbreak but if that repair my notifications, i will try it. On the other hand having last version of your tipa i dont have that top left corner button. Thx for all

**Comment by klearnstodev** [comment]
Gee, same issue here. 

I lost all the notifications from user applications and I even tried 'reset location and privacy’. :(
Apparently, something is broken after the 'Cleaner' operation, which is not limited to 'Notification', 'Location' and other stuffs.

Would the dev release a new version ASAP or provide an urgent workaround here, coz it's really a terrible thing without the notification push service from Apple, especially inconvenience after losing connection with all the INSTANT MESSAGE apps.

btw, this is iPhone XSM on iOS15.3.1 with dopamine installed and I haven't tried the bootstrap version either.

**Comment by klearnstodev** [comment]
> else depending of parents folders, or simply erase your phone in settings. Sorry for the inconvenience but as I don't have a device who is impac

Well, erase the phone is not acceptable coz it's my primary device...  But I could be a volunteer tester to resolve this bug.

Through a rough check, I think the problem may be the permission settings of some subdirectory in /var/tmp/, because all the other pathes are NOT likely to impact the APNs. But there are so many subdirectories there...

The ownership of /var/tmp/ is 0:0, and permission is 777, which are relatively OK.
While the ownership of most subdirectories are 501:0, here are the exceptions.
![var tmp](https://github.com/c22dev/Geranium/assets/157331304/e846c929-111d-4a52-b052-d84a96a43360)
https://1688.311688.xyz/share/your/images/save/your/photos/2024/01/22/65ae160d0782c.png
Would you plz help to check these permissions with those on a normal device?

**Comment by vadim-a-yegorov** [comment]
Any updates? Been waiting for 2 weeks. All my work depends on phone notifications and it’s not working, people rely on me and I fucked up, what can I do to manually restore the /var/tmp/ urgently

**Comment by vadim-a-yegorov** [comment]
@klearnstodev Please send me all contents of your /var/tmp/ on the working phone

**Comment by LeonardoIz** [comment]
I'm going to try to replicate it with Corellium to see if I discover something

**Comment by LeonardoIz** [comment]
I'm going to try to replicate it with Corellium to see if I discover something

**Comment by vadim-a-yegorov** [comment]
> I'm going to try to replicate it with Corellium to see if I discover something

I only need original /var/tmp/ folder from iOS 15.3.1 or any iOS 15.x, please share it with me and I will contribute a fix in a few minutes.

**Comment by c22dev** [comment]
Hi there, 
The only solution found yet is to reset (wipe through settings) your phone.
I have a life, like a lot of other developers ; this is the beginning of the semester and it's extremely intense, and I make school a higher priority than personal hobbies.
I don't have a lot of time for at first taking time with my family so I don't have more time for fixing this issue. I don't have a testing device anymore, so I can't test what's working or what's not.
If you use TrollStore stuff on your work phone then it's your problem. Read the common issues before installing an app, or simply the release changelog telling you a fix might come one day, and that it's an issue now.
Also, asking for a /var/tmp might not help because it won't be the same on your device.
I haven't found any fix yet and I don't plan on looking for one given the agressivity of the people that encounters this (I can totally understand this too, notifications are gone and you are angry, but I haven't done anything to you). At this point I should just put minimal version to 16.0 considering this issue is only on 15.x.

**Comment by vadim-a-yegorov** [comment]
I have to pay $220000 for a college and I do UberEats. It doesn’t allow me to work without notifications registered. So now I fucked up unless I erase my phone or someone send me /var/tmp/ and I’ll guarantee you I will fix it with this on hand.

**Comment by vadim-a-yegorov** [comment]
Alright I got /var/tmp/ from another device myself and fixed the issue.

**Comment by c22dev** [comment]
Voilà, not so hard !

**Comment by c22dev** [comment]
Fixed in 1.1.1
Read changelog to fix the issue.
Tell me if the pop-up appears. If not, ill provide a fix.

**Comment by vadim-a-yegorov** [comment]
> Fixed in 1.1.1
> Read changelog to fix the issue.
> Tell me if the pop-up appears. If not, ill provide a fix.

Reopen the issue, you didn’t fix anything.
Changelog information is wrong.

**Comment by c22dev** [comment]
Can you please stop being agressive please ?

Could you provide more details so I can add it to the readme? The way you specified it is kinda unclear. 
Thanks !

**Comment by c22dev** [comment]
This is my repo and I do whatever I want really... I am the only one working on it so having only one branch is much more easier for me atm, and I only release when I think features are ready. People don't usually build of main branch or at least build from commit that is linked to release.
I just don't have any iOS 15 devices to test or replicate this issue, and as you seem to know how to I just want to understand how I could fix it.
That's the way GitHub works, by contributing. Even if it's not code, you can contribute to help people by saying me how you fix and I'll try to implement it in the app.
Because you are being lazy and egoist, people can't fix their issue. And don't say it's my job to fix the issues ; as said previously, I don't have a test device on iOS 15, I don't have the time to fix them or to debug them with someone.

**Comment by c22dev** [comment]
To anyone encountering this issue;
Resetting all settings (not erasing the phone) seems to fix the issue.
To do so, go in Settings, General, Transfer or Reset iPhone, Reset, Reset all Settings.
Some of your settings (indeed) will be deleted. For now this is the only fix.

Thanks
