### ISSUE TITLE
English doesn't appear as a language in 1.0.1

### ISSUE THREAD

**Issue by k3v1nwrld** [c22dev/Geranium#3]
I updated to the latest version and still have the language issue. Funny thing is that i only have english set up as a language on my device, but have different keyboard languages that aren't english. I tried to switch to user registration and enable it through settings but that led to the same result.

**Comment by c22dev** [comment]
Yep, this is a known issue, however what language are you trying to set the app too ?

**Comment by c22dev** [comment]
Should have fixed in latest release : https://github.com/c22dev/Geranium/releases/latest

**Comment by k3v1nwrld** [comment]
Still doesnt let me set the language to english. Tried through the debug method and it changed the language to japanese

**Comment by c22dev** [comment]
This is extremely strange. The app is literally setting it to "en", which is English by default Can you screen record it to me ? Try uninstalling the app then reinstalling it.

**Comment by k3v1nwrld** [comment]
Uninstalled and reinstalled the latest version (1.0.2)

https://github.com/c22dev/Geranium/assets/75213647/478c8e9c-845a-442d-81fb-63871aae1038

**Comment by c22dev** [comment]
Try latest release (1.0.3) please
I am going crazy with this :)

**Comment by k3v1nwrld** [comment]
English shows up now, but when selecting it, it sets it to japanese again (defsult does the same)

**Comment by k3v1nwrld** [comment]
Btw are you sure you've included english when compiling the app?? Just checked the .app with filza and there is no en.lproj

**Comment by c22dev** [comment]
Please try downloading the same release again (I changed the file).

It's default. Should be picked. But will try to add English even if this is really weird.
As you can see I can't add en-US. 

<img width="263" alt="Capture d’écran 2024-01-15 à 02 01 27" src="https://github.com/c22dev/Geranium/assets/102235607/3b55cadb-67a4-4f39-9468-4647f6a8d712">

Latest release upload should fix, as instead of setting to `en` it sets to `en-US`. So yeah download it and install it again.

**Comment by k3v1nwrld** [comment]
Still having the same issue even tho i updated

**Comment by c22dev** [comment]
Okay... I'll try with British English. However, can you please try setting using the button ?

**Comment by k3v1nwrld** [comment]
Tbh i've been trying all the methods i can think of every time (button, debug, switching to user app and changing it thru settings)

**Comment by c22dev** [comment]
It's 2am here too. Good night tho

**Comment by c22dev** [comment]
Try 1.0.4 when you can.

**Comment by k3v1nwrld** [comment]
Tried 1.0.4 and it's working now. Thanks for the quick responses
